[servers]
v1_8_8 = "127.0.0.1:25566"
v1_12_2 = "127.0.0.1:25567"

[forced-hosts]
"*" = ["v1_8_8", "v1_12_2"]

[query]
enabled = true
port = 25565

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 300
connection-timeout = 5000
read-timeout = 30000
